=== Yuchen1108/panda3core/src/main/resources/de/uniulm/ki/panda3/symbolic/parser/xml/domain-2.0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

	Requested Changes:
		This is a list of changes that will break downward compability:
			- inline elements "leftHandSide" and "rightHandSide"
			- reorganize the usage of variables in methods: task nodes should get a list of variables instead of varDeclarations.
			  The variables may reference the varDeclarations of the method. This requires to add a taskNode to method as the
			  implemented task and maybe surround the subtasks with a "subTasks" element

-->

<!ELEMENT domain (meta*, documentation?, sortDeclaration*, constantDeclaration*, relationDeclaration*, decompositionAxiom*, taskSchemaDeclaration+, methodDeclaration*)>
<!ATTLIST domain name ID #REQUIRED>
<!ATTLIST domain type (non-hierarchical|pure-hierarchical|hybrid) #REQUIRED>

<!-- Documentation -->

<!ELEMENT documentation (#PCDATA)>

<!-- Sorts -->

<!ELEMENT sortDeclaration (documentation?, subSort*)>
<!ATTLIST sortDeclaration name ID #REQUIRED>
<!ATTLIST sortDeclaration type (abstract|concrete) #REQUIRED>
<!ELEMENT subSort EMPTY>
<!ATTLIST subSort sort IDREF #REQUIRED>

<!-- Relation Declarations -->

<!ELEMENT relationDeclaration (documentation?, argumentSort*)>
<!ATTLIST relationDeclaration name ID #REQUIRED>
<!ATTLIST relationDeclaration type (rigid|flexible) #REQUIRED>

<!ELEMENT argumentSort EMPTY>
<!ATTLIST argumentSort sort IDREF #REQUIRED>

<!-- Constant Declarations -->

<!ELEMENT constantDeclaration EMPTY>
<!ATTLIST constantDeclaration name ID #REQUIRED>
<!ATTLIST constantDeclaration sort IDREF #REQUIRED>

<!-- Variable Declarations -->

<!ELEMENT variableDeclaration EMPTY>
<!ATTLIST variableDeclaration name ID #REQUIRED>
<!ATTLIST variableDeclaration sort IDREF #REQUIRED>
<!ATTLIST variableDeclaration displayName CDATA "">

<!-- Terms -->

<!ELEMENT constant EMPTY>
<!ATTLIST constant name IDREF #REQUIRED>

<!ELEMENT variable EMPTY>
<!ATTLIST variable name IDREF #REQUIRED>

<!-- Formulas -->

<!ELEMENT atomic ((variable|constant)*)>
<!ATTLIST atomic relation IDREF #REQUIRED>

<!ELEMENT not (atomic|not|and|or|imply|forall|exists)>
<!ELEMENT imply ((atomic|not|and|or|imply|forall|exists), (atomic|not|and|or|imply|forall|exists))>
<!ELEMENT and (atomic|not|and|or|imply|forall|exists)+>
<!ELEMENT or (atomic|not|and|or|imply|forall|exists)+>
<!ELEMENT forall (variableDeclaration, (atomic|not|and|or|imply|forall|exists))>
<!ELEMENT exists (variableDeclaration, (atomic|not|and|or|imply|forall|exists))>

<!-- Decomposition Axioms -->

<!ELEMENT decompositionAxiom (documentation?, variableDeclaration+, leftHandSide, rightHandSide)>
<!ATTLIST decompositionAxiom name ID #REQUIRED>
<!ELEMENT leftHandSide (atomic)>
<!ELEMENT rightHandSide ((atomic|not|and|or|imply|forall|exists)+)>
<!-- decomposition axioms are interpreted as equivalence of atomic and enclosed formula.
     The list of formulae is interpreted as a disjunction -->

<!-- Task Declarations -->

<!ELEMENT taskSchemaDeclaration (documentation?, variableDeclaration*, (atomic|not|and|or|imply|forall|exists|true), (atomic|not|and|or|imply|forall|exists|true))>
<!ATTLIST taskSchemaDeclaration name ID #REQUIRED>
<!ATTLIST taskSchemaDeclaration type (primitive|complex) #REQUIRED>
<!ATTLIST taskSchemaDeclaration cost CDATA "1">

<!ELEMENT true EMPTY>

<!-- Method Declarations -->

<!ELEMENT methodDeclaration (documentation?, variableDeclaration*, taskNode+, orderingConstraint*, (valueRestriction|sortRestriction)*, causalLink*)>
<!ATTLIST methodDeclaration name ID #REQUIRED>
<!ATTLIST methodDeclaration taskSchema IDREF #REQUIRED>

<!ELEMENT taskNode (variableDeclaration*)>
<!ATTLIST taskNode name ID #REQUIRED>
<!ATTLIST taskNode taskSchema IDREF #REQUIRED>
<!ATTLIST taskNode displayName CDATA "">

<!ELEMENT orderingConstraint EMPTY>
<!ATTLIST orderingConstraint predecessor IDREF #REQUIRED>
<!ATTLIST orderingConstraint successor IDREF #REQUIRED>

<!ELEMENT valueRestriction (variable|constant)>
<!ATTLIST valueRestriction type (eq|neq) #REQUIRED>
<!ATTLIST valueRestriction variable IDREF #REQUIRED>

<!ELEMENT sortRestriction EMPTY>
<!ATTLIST sortRestriction type (eq|neq) #REQUIRED>
<!ATTLIST sortRestriction variable IDREF #REQUIRED>
<!ATTLIST sortRestriction sort IDREF #REQUIRED>

<!ELEMENT causalLink (atomic|not|and|or|imply|forall|exists)>
<!ATTLIST causalLink producer IDREF #REQUIRED>
<!ATTLIST causalLink consumer IDREF #REQUIRED>

=== Yuchen1108/panda3core/src/test/resources/de/uniulm/ki/panda3/symbolic/parser/xml/satellite2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE domainModel SYSTEM "domain-2.0.dtd">

<domain name="satellite2" type="pure-hierarchical">
    <documentation>This is a hierarchical version of the IPC satellite domain.</documentation>

    <sortDeclaration name="instrument" type="concrete"/>
    <sortDeclaration name="satellite" type="concrete"/>
    <sortDeclaration name="mode" type="concrete"/>
    <sortDeclaration name="calib_direction" type="concrete">
        <documentation>These directions are used for instrument calibration only.</documentation>
    </sortDeclaration>
    <sortDeclaration name="image_direction" type="concrete"/>
    <sortDeclaration name="direction" type="abstract">
        <documentation>Directions are all kinds of phenomenons and targets to which the satellite and its instruments
            can be directed.
        </documentation>
        <subSort sort="calib_direction"/>
        <subSort sort="image_direction"/>
    </sortDeclaration>

    <relationDeclaration name="on_board" type="rigid">
        <argumentSort sort="instrument"/>
        <argumentSort sort="satellite"/>
    </relationDeclaration>
    <relationDeclaration name="supports" type="rigid">
        <argumentSort sort="instrument"/>
        <argumentSort sort="mode"/>
    </relationDeclaration>
    <relationDeclaration name="pointing" type="flexible">
        <argumentSort sort="satellite"/>
        <argumentSort sort="direction"/>
    </relationDeclaration>
    <relationDeclaration name="power_avail" type="flexible">
        <argumentSort sort="satellite"/>
    </relationDeclaration>
    <relationDeclaration name="power_on" type="flexible">
        <argumentSort sort="instrument"/>
    </relationDeclaration>
    <relationDeclaration name="calibrated" type="flexible">
        <argumentSort sort="instrument"/>
    </relationDeclaration>
    <relationDeclaration name="have_image" type="flexible">
        <argumentSort sort="image_direction"/>
        <argumentSort sort="mode"/>
    </relationDeclaration>
    <!-- changed calibration target to rigid -bs -->
    <relationDeclaration name="calibration_target" type="rigid">
        <documentation>This relation models targets that are used for calibrating a specific instrument.</documentation>
        <argumentSort sort="instrument"/>
        <argumentSort sort="calib_direction"/>
    </relationDeclaration>

    <taskSchemaDeclaration name="turn_to" type="primitive">
        <documentation>
            The parameters of turning are:
            1. the satellite that is turning
            2. the direction the satellite is pointing to after turning
            3. the direction the satellite is pointing to before turning
        </documentation>
        <variableDeclaration name="t_s" sort="satellite"/>
        <variableDeclaration name="t_d_new" sort="direction"/>
        <variableDeclaration name="t_d_prev" sort="direction"/>

        <atomic relation="pointing">
            <variable name="t_s"/>
            <variable name="t_d_prev"/>
        </atomic>
        <and>
            <atomic relation="pointing">
                <variable name="t_s"/>
                <variable name="t_d_new"/>
            </atomic>
            <not>
                <atomic relation="pointing">
                    <variable name="t_s"/>
                    <variable name="t_d_prev"/>
                </atomic>
            </not>
        </and>
    </taskSchemaDeclaration>

    <taskSchemaDeclaration name="switch_on" type="primitive">
        <documentation>
            This action turns on the power supply for a satellite's instrument. Please note that switching on an
            on-board unit de-calibrates it and allocates all energy resources on the satellite.
        </documentation>
        <variableDeclaration name="so_i" sort="instrument"/>
        <variableDeclaration name="so_s" sort="satellite"/>

        <and>
            <atomic relation="on_board">
                <variable name="so_i"/>
                <variable name="so_s"/>
            </atomic>
            <atomic relation="power_avail">
                <variable name="so_s"/>
            </atomic>
        </and>
        <and>
            <atomic relation="power_on">
                <variable name="so_i"/>
            </atomic>
            <not>
                <atomic relation="calibrated">
                    <variable name="so_i"/>
                </atomic>
            </not>
            <not>
                <atomic relation="power_avail">
                    <variable name="so_s"/>
                </atomic>
            </not>
        </and>
    </taskSchemaDeclaration>

    <taskSchemaDeclaration name="switch_off" type="primitive">
        <documentation>
            This action turns off the power supply for a satellite's instrument. Switching off an
            on-board unit makes all energy resources on the satellite available again.
        </documentation>
        <variableDeclaration name="sof_i" sort="instrument"/>
        <variableDeclaration name="sof_s" sort="satellite"/>

        <and>
            <atomic relation="on_board">
                <variable name="sof_i"/>
                <variable name="sof_s"/>
            </atomic>
            <atomic relation="power_on">
                <variable name="sof_i"/>
            </atomic>
        </and>
        <and>
            <not>
                <atomic relation="power_on">
                    <variable name="sof_i"/>
                </atomic>
            </not>
            <atomic relation="power_avail">
                <variable name="sof_s"/>
            </atomic>
        </and>
    </taskSchemaDeclaration>

    <taskSchemaDeclaration name="calibrate" type="primitive">
        <variableDeclaration name="c_s" sort="satellite"/>
        <variableDeclaration name="c_i" sort="instrument"/>
        <variableDeclaration name="c_d" sort="calib_direction"/>

        <and>
            <atomic relation="on_board">
                <variable name="c_i"/>
                <variable name="c_s"/>
            </atomic>
            <atomic relation="calibration_target">
                <variable name="c_i"/>
                <variable name="c_d"/>
            </atomic>
            <atomic relation="pointing">
                <variable name="c_s"/>
                <variable name="c_d"/>
            </atomic>
            <atomic relation="power_on">
                <variable name="c_i"/>
            </atomic>

        </and>
        <and>
            <atomic relation="calibrated">
                <variable name="c_i"/>
            </atomic>
        </and>
    </taskSchemaDeclaration>

    <taskSchemaDeclaration name="take_image" type="primitive">
        <variableDeclaration name="ti_s" sort="satellite"/>
        <variableDeclaration name="ti_d" sort="image_direction"/>
        <variableDeclaration name="ti_i" sort="instrument"/>
        <variableDeclaration name="ti_m" sort="mode"/>

        <and>
            <atomic relation="calibrated">
                <variable name="ti_i"/>
            </atomic>
            <atomic relation="pointing">
                <variable name="ti_s"/>
                <variable name="ti_d"/>
            </atomic>
            <atomic relation="on_board">
                <variable name="ti_i"/>
                <variable name="ti_s"/>
            </atomic>
            <atomic relation="power_on">
                <variable name="ti_i"/>
            </atomic>
            <atomic relation="supports">
                <variable name="ti_i"/>
                <variable name="ti_m"/>
            </atomic>
        </and>
        <atomic relation="have_image">
            <variable name="ti_d"/>
            <variable name="ti_m"/>
        </atomic>
    </taskSchemaDeclaration>

    <!-- ############# Komplexe Taks #################-->

    <!-- holt bild von gegebenen direction im gegebenen mode macht dabei:
    [ai]							value restriction: ?s muss bei allen 3 gleich sein
    [tt]								[] = nicht immer noetig
    take_image
    -->
    <taskSchemaDeclaration name="do_observation" type="complex">
        <variableDeclaration name="do_d" sort="image_direction"/>
        <variableDeclaration name="do_m" sort="mode"/>

        <!-- vorbed oder von einem subtask erfuellt fuer alle vorbedingungen der subtasks -->
        <true/>
        <atomic relation="have_image">
            <variable name="do_d"/>
            <variable name="do_m"/>
        </atomic>
    </taskSchemaDeclaration>

    <!-- setz power on fuer gegebenes instrument auf einem gegebenen satelliten macht dabei:
    [s_off]				[] = nicht immer noetig
    s_on
    auto_calibrate
    -->
    <taskSchemaDeclaration name="activate_instrument" type="complex">
        <documentation>
            Activating an instrument optionally includes turning off other instruments on the same satellite in order
            to provide energy, followed by turning on the instrument.
        </documentation>
        <variableDeclaration name="ai_s" sort="satellite"/>
        <variableDeclaration name="ai_i" sort="instrument"/>

        <atomic relation="on_board">
            <variable name="ai_i"/>
            <variable name="ai_s"/>
        </atomic>
        <atomic relation="power_on">
            <variable name="ai_i"/>
        </atomic>
    </taskSchemaDeclaration>

    <!-- dreht und kalibriert oder kalibriert sich auf ein kalibrierungs target ein instrument eines gegebenen satelliten
    [turn_to]
    calibrate

    value restriction
    tt ?d = cal ?d
    und cal ?d = calibration target
    -->
    <taskSchemaDeclaration name="auto_calibrate" type="complex">
        <documentation>
            Manages the calibration of the given instrument. This may include turning the satellite's instrument to the
            calibration target first.
        </documentation>
        <variableDeclaration name="ac_s" sort="satellite"/>
        <variableDeclaration name="ac_i" sort="instrument"/>

        <and>
