=== Yuchen1108/panda3core/src/main/resources/de/uniulm/ki/panda3/symbolic/parser/xml/problem-2.0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

    Requested Changes:
        This is a list of changes that will break downward compability:
            - add varDeclarations to problem and replace attribute "varDeclaration" in element "taskNode" with "variable"
            - remove "fact" from element list of "goalStateDescription", "forall", "exists", "and", "or", "not", "preference", "causalLink"

-->

<!ELEMENT problem (documentation?, constantDeclaration*, initialState, goals?, initialTaskNetwork?)>
<!ATTLIST problem name ID #REQUIRED>
<!ATTLIST problem domain CDATA #REQUIRED>
<!ATTLIST problem type (non-hierarchical|pure-hierarchical|hybrid) #REQUIRED>

<!-- Documentation -->

<!ELEMENT documentation (#PCDATA)>

<!-- Constant Declarations -->

<!ELEMENT constantDeclaration EMPTY>
<!ATTLIST constantDeclaration name ID #REQUIRED>
<!ATTLIST constantDeclaration sort CDATA #REQUIRED>

<!-- Variable Declarations -->

<!ELEMENT variableDeclaration EMPTY>
<!ATTLIST variableDeclaration name ID #REQUIRED>
<!ATTLIST variableDeclaration sort CDATA #REQUIRED>

<!-- Terms -->

<!-- The name attribute of a constant is not an IDREF as a constant can also be defined in a domain -->
<!ELEMENT constant EMPTY>
<!ATTLIST constant name CDATA #REQUIRED>

<!ELEMENT variable EMPTY>
<!ATTLIST variable name IDREF #REQUIRED>

<!-- Formulas -->

<!ELEMENT atomic ((variable|constant)*)>
<!ATTLIST atomic relation CDATA #REQUIRED>

<!ELEMENT fact (constant*)>
<!ATTLIST fact relation CDATA #REQUIRED>

<!ELEMENT not (atomic|fact|not|and|or|imply|forall|exists)>
<!ELEMENT imply ((atomic|not|and|or|imply|forall|exists), (atomic|not|and|or|imply|forall|exists))>
<!ELEMENT and (atomic|fact|not|and|or|imply|forall|exists)+>
<!ELEMENT or (atomic|fact|not|and|or|imply|forall|exists)+>
<!ELEMENT forall (variableDeclaration, (atomic|fact|not|and|or|imply|forall|exists))>
<!ELEMENT exists (variableDeclaration, (atomic|fact|not|and|or|imply|forall|exists))>

<!-- Initial and Goal State -->

<!ELEMENT initialState (documentation?, fact*)>
<!ELEMENT goals (documentation?, (atomic|fact|not|and|or|imply|forall|exists|preference)*)>

<!ELEMENT preference (atomic|fact|not|and|or|imply|forall|exists)>
<!ATTLIST preference name CDATA #REQUIRED>

<!-- Initial Task Network -->

<!ELEMENT initialTaskNetwork (documentation?, taskNode+, orderingConstraint*, (valueRestriction|sortRestriction)*, causalLink*)>

<!ELEMENT taskNode (variableDeclaration*)>
<!ATTLIST taskNode name ID #REQUIRED>
<!ATTLIST taskNode taskSchema CDATA #REQUIRED>

<!ELEMENT orderingConstraint EMPTY>
<!ATTLIST orderingConstraint predecessor IDREF #REQUIRED>
<!ATTLIST orderingConstraint successor IDREF #REQUIRED>

<!ELEMENT valueRestriction (variable|constant)>
<!ATTLIST valueRestriction type (eq|neq) #REQUIRED>
<!ATTLIST valueRestriction variable IDREF #REQUIRED>

<!ELEMENT sortRestriction EMPTY>
<!ATTLIST sortRestriction type (eq|neq) #REQUIRED>
<!ATTLIST sortRestriction variable IDREF #REQUIRED>
<!ATTLIST sortRestriction sort CDATA #REQUIRED>

<!ELEMENT causalLink (atomic|fact|not|and|or|imply|forall|exists)>
<!ATTLIST causalLink producer IDREF #REQUIRED>
<!ATTLIST causalLink consumer IDREF #REQUIRED>

=== Yuchen1108/panda3core/src/test/resources/de/uniulm/ki/panda3/symbolic/parser/xml/OrganizeMeeting_Small.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE problem SYSTEM "problem-2.0.dtd">
<problem domain="SmartPhone" name="OrganizeMeeting_Small" type="pure-hierarchical">
   <constantDeclaration name="agenda" sort="Agenda"/>
   <constantDeclaration name="appointmentForMeeting" sort="Appointment"/>
   <constantDeclaration name="contact1" sort="Contact"/>
   <constantDeclaration name="contact2" sort="Contact"/>
   <constantDeclaration name="headOfDepartment" sort="Person"/>
   <constantDeclaration name="peer1" sort="Person"/>
   <constantDeclaration name="headOfDepartmentEMailAddress"
      sort="EMailAddress"/>
   <constantDeclaration name="peer1EMailAddress" sort="EMailAddress"/>
   <constantDeclaration name="dateForMeeting" sort="Date"/>
   <constantDeclaration name="email1" sort="EMail"/>
   <constantDeclaration name="email2" sort="EMail"/>
   <constantDeclaration name="account1" sort="EMailAccount"/>
   <constantDeclaration name="taskCreateHandout" sort="Task"/>
   <constantDeclaration name="room101" sort="Location"/>
   <constantDeclaration name="headOfDepartmentPicture" sort="Picture"/>
   <constantDeclaration name="peer1Picture" sort="Picture"/>
   <initialState>
      <fact relation="associated_Contact">
         <constant name="contact1"/>
         <constant name="headOfDepartment"/>
      </fact>
      <fact relation="associated_Contact">
         <constant name="contact2"/>
         <constant name="peer1"/>
      </fact>
      <fact relation="associated_Picture">
         <constant name="contact1"/>
         <constant name="headOfDepartmentPicture"/>
      </fact>
      <fact relation="associated_Picture">
         <constant name="contact2"/>
         <constant name="peer1Picture"/>
      </fact>
      <fact relation="created">
         <constant name="contact1"/>
      </fact>
      <fact relation="haveInformation_Contactable">
         <constant name="headOfDepartment"/>
         <constant name="headOfDepartmentEMailAddress"/>
      </fact>
      <fact relation="haveInformation_Contactable">
         <constant name="peer1"/>
         <constant name="peer1EMailAddress"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="agenda"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="dateForMeeting"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="headOfDepartmentPicture"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="peer1Picture"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="room101"/>
      </fact>
      <fact relation="inMode_Home"/>
      <fact relation="inUse">
         <constant name="contact1"/>
      </fact>
      <fact relation="inUse">
         <constant name="contact2"/>
      </fact>
      <fact relation="isFavourite">
         <constant name="contact1"/>
      </fact>
      <fact relation="isFavourite">
         <constant name="contact2"/>
      </fact>
      <fact relation="selected">
         <constant name="account1"/>
      </fact>
      <fact relation="created">
         <constant name="contact2"/>
      </fact>
   </initialState>
   <goals>
      <fact relation="hasInformation_Regular">
         <constant name="headOfDepartment"/>
         <constant name="dateForMeeting"/>
      </fact>
      <fact relation="hasInformation_Regular">
         <constant name="peer1"/>
         <constant name="dateForMeeting"/>
      </fact>
      <fact relation="hasInformation_Regular">
         <constant name="headOfDepartment"/>
         <constant name="room101"/>
      </fact>
      <fact relation="hasInformation_Regular">
         <constant name="peer1"/>
         <constant name="room101"/>
      </fact>
      <fact relation="hasInformation_Regular">
         <constant name="headOfDepartment"/>
         <constant name="agenda"/>
      </fact>
      <fact relation="hasInformation_Regular">
         <constant name="peer1"/>
         <constant name="agenda"/>
      </fact>
      <fact relation="created">
         <constant name="appointmentForMeeting"/>
      </fact>
      <fact relation="created">
         <constant name="taskCreateHandout"/>
      </fact>
   </goals>
   <initialTaskNetwork>
      <taskNode name="attachMultipleInformationToEmail1" taskSchema="attachMultipleInformation">
         <variableDeclaration
            name="attachMultipleInformationToEmail1_message" sort="Message"/>
      </taskNode>
	  <taskNode name="attachMultipleInformationToEmail2" taskSchema="attachMultipleInformation">
         <variableDeclaration
            name="attachMultipleInformationToEmail2_message" sort="Message"/>
      </taskNode>
      <taskNode name="sendEmail1ToHeadOfDepartment" taskSchema="send_EMail">
         <variableDeclaration name="sendEmail1ToHeadOfDepartment_receipient" sort="Contactable"/>
         <variableDeclaration name="sendEmail1ToHeadOfDepartment_email" sort="EMail"/>
      </taskNode>
      <taskNode name="sendEmail2ToPeer1" taskSchema="send_EMail">
         <variableDeclaration name="sendEmail2ToPeer1_receipient" sort="Contactable"/>
         <variableDeclaration name="sendEmail2ToPeer1_email" sort="EMail"/>
      </taskNode>
      <taskNode name="create_AppointmentForMeeting" taskSchema="create_Appointment">
         <variableDeclaration name="create_AppointmentForMeeting_appointment" sort="Appointment"/>
         <variableDeclaration name="create_AppointmentForMeeting_location" sort="Location"/>
         <variableDeclaration name="create_AppointmentForMeeting_date" sort="Date"/>
      </taskNode>
      <taskNode name="create_HandoutForMeeting" taskSchema="create_Task">
         <variableDeclaration name="create_HandoutForMeeting_task" sort="Task"/>
      </taskNode>
      <taskNode name="extractsMultipleInformation_headOfDepartment" taskSchema="extractsMultipleInformation">
         <variableDeclaration
            name="extractsMultipleInformation_headOfDepartment_contactable" sort="Contactable"/>
         <variableDeclaration
            name="extractsMultipleInformation_headOfDepartment_message" sort="Message"/>
      </taskNode>
      <taskNode name="extractsMultipleInformation_peer1" taskSchema="extractsMultipleInformation">
         <variableDeclaration
            name="extractsMultipleInformation_peer1_contactable" sort="Contactable"/>
         <variableDeclaration
            name="extractsMultipleInformation_peer1_message" sort="Message"/>
      </taskNode>
      <orderingConstraint
         predecessor="attachMultipleInformationToEmail1" successor="sendEmail1ToHeadOfDepartment"/>
      <orderingConstraint
         predecessor="attachMultipleInformationToEmail2" successor="sendEmail2ToPeer1"/>
      <orderingConstraint predecessor="sendEmail1ToHeadOfDepartment" successor="extractsMultipleInformation_headOfDepartment"/>
      <orderingConstraint predecessor="sendEmail2ToPeer1" successor="extractsMultipleInformation_peer1"/>
      <valueRestriction type="eq" variable="attachMultipleInformationToEmail1_message">
         <constant name="email1"/>
      </valueRestriction>
	  <valueRestriction type="eq" variable="attachMultipleInformationToEmail2_message">
         <constant name="email2"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="sendEmail1ToHeadOfDepartment_email">
         <constant name="email1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="sendEmail2ToPeer1_email">
         <constant name="email2"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="sendEmail1ToHeadOfDepartment_receipient">
         <constant name="headOfDepartment"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="sendEmail2ToPeer1_receipient">
         <constant name="peer1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="create_AppointmentForMeeting_appointment">
         <constant name="appointmentForMeeting"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="create_AppointmentForMeeting_date">
         <constant name="dateForMeeting"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="create_AppointmentForMeeting_location">
         <constant name="room101"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="create_HandoutForMeeting_task">
         <constant name="taskCreateHandout"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="extractsMultipleInformation_headOfDepartment_contactable">
         <constant name="headOfDepartment"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="extractsMultipleInformation_peer1_contactable">
         <constant name="peer1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="extractsMultipleInformation_headOfDepartment_message">
         <constant name="email1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="extractsMultipleInformation_peer1_message">
         <constant name="email2"/>
      </valueRestriction>
      <causalLink
         consumer="extractsMultipleInformation_headOfDepartment" producer="sendEmail1ToHeadOfDepartment">
         <atomic relation="hasReceived">
            <constant name="headOfDepartment"/>
            <constant name="email1"/>
         </atomic>
      </causalLink>
      <causalLink consumer="extractsMultipleInformation_peer1" producer="sendEmail2ToPeer1">
         <atomic relation="hasReceived">
            <constant name="peer1"/>
            <constant name="email2"/>
         </atomic>
      </causalLink>
   </initialTaskNetwork>
</problem>

=== Yuchen1108/panda3core/src/test/resources/de/uniulm/ki/panda3/symbolic/parser/xml/sat-A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE problem SYSTEM "problem-2.0.dtd">
<problem domain="satellite2" name="sat-A-simple" type="pure-hierarchical">
   <constantDeclaration name="instrument0" sort="instrument"/>
   <constantDeclaration name="satellite0" sort="satellite"/>
   <constantDeclaration name="thermograph0" sort="mode"/>
   <constantDeclaration name="GroundStation2" sort="calib_direction"/>
   <constantDeclaration name="Phenomenon6" sort="image_direction"/>
   <constantDeclaration name="Phenomenon4" sort="image_direction"/>
   <initialState>
      <fact relation="on_board">
         <constant name="instrument0"/>
         <constant name="satellite0"/>
      </fact>
      <fact relation="supports">
         <constant name="instrument0"/>
         <constant name="thermograph0"/>
      </fact>
      <fact relation="calibration_target">
         <constant name="instrument0"/>
         <constant name="GroundStation2"/>
      </fact>
      <fact relation="power_avail">
         <constant name="satellite0"/>
      </fact>
      <fact relation="pointing">
         <constant name="satellite0"/>
         <constant name="Phenomenon6"/>
      </fact>
   </initialState>
   <initialTaskNetwork>
      <taskNode name="observation1" taskSchema="do_observation">
         <variableDeclaration name="direction1" sort="image_direction"/>
         <variableDeclaration name="mode1" sort="mode"/>
      </taskNode>
      <valueRestriction type="eq" variable="direction1">
         <constant name="Phenomenon4"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="mode1">
         <constant name="thermograph0"/>
      </valueRestriction>
   </initialTaskNetwork>
</problem>

=== Yuchen1108/panda3core/src/test/resources/de/uniulm/ki/panda3/symbolic/parser/xml/satellite2-P-abstract-2obs-2sat-2mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE problem SYSTEM "problem-2.0.dtd">
<problem domain="satellite2" name="abstract_2_observations_2_satellites_2_modes" type="pure-hierarchical">
   <documentation>
        This problem is intended to have two solutions: either observations are performed in parallel
        or both are performed on one satellite that has to switch its instrument.
        We can find a solution with 13 primitive tasks (including initial and goal tasks) after 28 cycles
        in manual mode (with 1 backtracking, fringe contains two plans at the end of the search). This solution
        is obtained when one satellite takes two images in series.
        We can find a solution with 12 primitive tasks (including initial and goal tasks) after 25 cycles
        in manual mode (without backtracking, fringe contains two plans at the end of the search). This solution
        is obtained when images are taken in parallel.
    </documentation>
   <constantDeclaration name="instrument01" sort="instrument"/>
   <constantDeclaration name="satellite0" sort="satellite"/>
   <constantDeclaration name="thermograph" sort="mode"/>
   <constantDeclaration name="GroundStation0" sort="calib_direction"/>
   <constantDeclaration name="instrument02" sort="instrument"/>
   <constantDeclaration name="x_ray" sort="mode"/>
   <constantDeclaration name="Phenomenon6" sort="image_direction"/>
   <constantDeclaration name="instrument1" sort="instrument"/>
   <constantDeclaration name="satellite1" sort="satellite"/>
   <constantDeclaration name="GroundStation1" sort="calib_direction"/>
   <constantDeclaration name="Phenomenon7" sort="image_direction"/>
   <constantDeclaration name="Phenomenon4" sort="image_direction"/>
   <constantDeclaration name="Star5" sort="image_direction"/>
   <initialState>
      <!-- instruments on board the first satellite -->
      <fact relation="on_board">
         <constant name="instrument01"/>
         <constant name="satellite0"/>
      </fact>
      <fact relation="supports">
         <constant name="instrument01"/>
         <constant name="thermograph"/>
      </fact>
      <fact relation="calibration_target">
         <constant name="instrument01"/>
         <constant name="GroundStation0"/>
      </fact>
      <fact relation="on_board">
         <constant name="instrument02"/>
         <constant name="satellite0"/>
      </fact>
      <fact relation="supports">
         <constant name="instrument02"/>
         <constant name="x_ray"/>
      </fact>
      <fact relation="calibration_target">
         <constant name="instrument02"/>
         <constant name="GroundStation0"/>
      </fact>
      <fact relation="power_avail">
         <constant name="satellite0"/>
      </fact>
      <fact relation="pointing">
         <constant name="satellite0"/>
         <constant name="Phenomenon6"/>
      </fact>
      <!-- instrument on board the second satellite -->
      <fact relation="on_board">
         <constant name="instrument1"/>
         <constant name="satellite1"/>
      </fact>
      <fact relation="supports">
         <constant name="instrument1"/>
         <constant name="thermograph"/>
      </fact>
      <fact relation="calibration_target">
         <constant name="instrument1"/>
         <constant name="GroundStation1"/>
      </fact>
      <fact relation="power_avail">
         <constant name="satellite1"/>
      </fact>
      <fact relation="pointing">
         <constant name="satellite1"/>
         <constant name="Phenomenon7"/>
      </fact>
   </initialState>
   <initialTaskNetwork>
      <taskNode name="observation1" taskSchema="do_observation">
         <variableDeclaration name="direction1" sort="image_direction"/>
         <variableDeclaration name="mode1" sort="mode"/>
      </taskNode>
      <taskNode name="observation2" taskSchema="do_observation">
         <variableDeclaration name="direction2" sort="image_direction"/>
         <variableDeclaration name="mode2" sort="mode"/>
      </taskNode>
      <valueRestriction type="eq" variable="direction1">
         <constant name="Phenomenon4"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="mode1">
         <constant name="thermograph"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="direction2">
         <constant name="Star5"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="mode2">
         <constant name="x_ray"/>
      </valueRestriction>
   </initialTaskNetwork>
</problem>
