=== Yuchen1108/panda3core/src/main/resources/de/uniulm/ki/panda3/symbolic/parser/xml/problem-2.0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

    Requested Changes:
        This is a list of changes that will break downward compability:
            - add varDeclarations to problem and replace attribute "varDeclaration" in element "taskNode" with "variable"
            - remove "fact" from element list of "goalStateDescription", "forall", "exists", "and", "or", "not", "preference", "causalLink"

-->

<!ELEMENT problem (documentation?, constantDeclaration*, initialState, goals?, initialTaskNetwork?)>
<!ATTLIST problem name ID #REQUIRED>
<!ATTLIST problem domain CDATA #REQUIRED>
<!ATTLIST problem type (non-hierarchical|pure-hierarchical|hybrid) #REQUIRED>

<!-- Documentation -->

<!ELEMENT documentation (#PCDATA)>

<!-- Constant Declarations -->

<!ELEMENT constantDeclaration EMPTY>
<!ATTLIST constantDeclaration name ID #REQUIRED>
<!ATTLIST constantDeclaration sort CDATA #REQUIRED>

<!-- Variable Declarations -->

<!ELEMENT variableDeclaration EMPTY>
<!ATTLIST variableDeclaration name ID #REQUIRED>
<!ATTLIST variableDeclaration sort CDATA #REQUIRED>

<!-- Terms -->

<!-- The name attribute of a constant is not an IDREF as a constant can also be defined in a domain -->
<!ELEMENT constant EMPTY>
<!ATTLIST constant name CDATA #REQUIRED>

<!ELEMENT variable EMPTY>
<!ATTLIST variable name IDREF #REQUIRED>

<!-- Formulas -->

<!ELEMENT atomic ((variable|constant)*)>
<!ATTLIST atomic relation CDATA #REQUIRED>

<!ELEMENT fact (constant*)>
<!ATTLIST fact relation CDATA #REQUIRED>

<!ELEMENT not (atomic|fact|not|and|or|imply|forall|exists)>
<!ELEMENT imply ((atomic|not|and|or|imply|forall|exists), (atomic|not|and|or|imply|forall|exists))>
<!ELEMENT and (atomic|fact|not|and|or|imply|forall|exists)+>
<!ELEMENT or (atomic|fact|not|and|or|imply|forall|exists)+>
<!ELEMENT forall (variableDeclaration, (atomic|fact|not|and|or|imply|forall|exists))>
<!ELEMENT exists (variableDeclaration, (atomic|fact|not|and|or|imply|forall|exists))>

<!-- Initial and Goal State -->

<!ELEMENT initialState (documentation?, fact*)>
<!ELEMENT goals (documentation?, (atomic|fact|not|and|or|imply|forall|exists|preference)*)>

<!ELEMENT preference (atomic|fact|not|and|or|imply|forall|exists)>
<!ATTLIST preference name CDATA #REQUIRED>

<!-- Initial Task Network -->

<!ELEMENT initialTaskNetwork (documentation?, taskNode+, orderingConstraint*, (valueRestriction|sortRestriction)*, causalLink*)>

<!ELEMENT taskNode (variableDeclaration*)>
<!ATTLIST taskNode name ID #REQUIRED>
<!ATTLIST taskNode taskSchema CDATA #REQUIRED>

<!ELEMENT orderingConstraint EMPTY>
<!ATTLIST orderingConstraint predecessor IDREF #REQUIRED>
<!ATTLIST orderingConstraint successor IDREF #REQUIRED>

<!ELEMENT valueRestriction (variable|constant)>
<!ATTLIST valueRestriction type (eq|neq) #REQUIRED>
<!ATTLIST valueRestriction variable IDREF #REQUIRED>

<!ELEMENT sortRestriction EMPTY>
<!ATTLIST sortRestriction type (eq|neq) #REQUIRED>
<!ATTLIST sortRestriction variable IDREF #REQUIRED>
<!ATTLIST sortRestriction sort CDATA #REQUIRED>

<!ELEMENT causalLink (atomic|fact|not|and|or|imply|forall|exists)>
<!ATTLIST causalLink producer IDREF #REQUIRED>
<!ATTLIST causalLink consumer IDREF #REQUIRED>

=== Yuchen1108/panda3core/src/test/resources/de/uniulm/ki/panda3/symbolic/parser/xml/01--p01-complete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE problem SYSTEM "problem-2.0.dtd">
<problem domain="woodworking" name="woodworking01-hierarchical" type="pure-hierarchical">
   <constantDeclaration name="grinder0" sort="grinder"/>
   <constantDeclaration name="planer0" sort="planer"/>
   <constantDeclaration name="spray-varnisher0" sort="spray-varnisher"/>
   <constantDeclaration name="red" sort="acolour"/>
   <constantDeclaration name="black" sort="acolour"/>
   <constantDeclaration name="pine" sort="awood"/>
   <constantDeclaration name="teak" sort="awood"/>
   <constantDeclaration name="p0" sort="part"/>
   <constantDeclaration name="p2" sort="part"/>
   <initialState>
      <fact relation="grind-treatment-change">
         <constant name="varnished"/>
         <constant name="colourfragments"/>
      </fact>
      <fact relation="grind-treatment-change">
         <constant name="glazed"/>
         <constant name="untreated"/>
      </fact>
      <fact relation="grind-treatment-change">
         <constant name="untreated"/>
         <constant name="untreated"/>
      </fact>
      <fact relation="grind-treatment-change">
         <constant name="colourfragments"/>
         <constant name="untreated"/>
      </fact>
      <fact relation="is-smooth">
         <constant name="smooth"/>
      </fact>
      <fact relation="is-smooth">
         <constant name="verysmooth"/>
      </fact>
      <fact relation="has-colour">
         <constant name="spray-varnisher0"/>
         <constant name="natural"/>
      </fact>
      <fact relation="has-colour">
         <constant name="spray-varnisher0"/>
         <constant name="red"/>
      </fact>
      <fact relation="available">
         <constant name="p0"/>
      </fact>
      <fact relation="colour">
         <constant name="p0"/>
         <constant name="red"/>
      </fact>
      <fact relation="wood">
         <constant name="p0"/>
         <constant name="pine"/>
      </fact>
      <fact relation="surface-condition">
         <constant name="p0"/>
         <constant name="smooth"/>
      </fact>
      <fact relation="treatment">
         <constant name="p0"/>
         <constant name="varnished"/>
      </fact>
      <fact relation="goalsize">
         <constant name="p0"/>
         <constant name="small"/>
      </fact>
      <fact relation="available">
         <constant name="p2"/>
      </fact>
      <fact relation="colour">
         <constant name="p2"/>
         <constant name="natural"/>
      </fact>
      <fact relation="wood">
         <constant name="p2"/>
         <constant name="teak"/>
      </fact>
      <fact relation="surface-condition">
         <constant name="p2"/>
         <constant name="verysmooth"/>
      </fact>
      <fact relation="treatment">
         <constant name="p2"/>
         <constant name="varnished"/>
      </fact>
      <fact relation="goalsize">
         <constant name="p2"/>
         <constant name="large"/>
      </fact>
   </initialState>
   <goals>
      <fact relation="available">
         <constant name="p0"/>
      </fact>
      <fact relation="colour">
         <constant name="p0"/>
         <constant name="natural"/>
      </fact>
      <fact relation="wood">
         <constant name="p0"/>
         <constant name="pine"/>
      </fact>
      <!--
      <fact relation="available">
         <constant name="p1"/>
      </fact>
      <fact relation="colour">
         <constant name="p1"/>
         <constant name="natural"/>
      </fact>
      <fact relation="wood">
         <constant name="p1"/>
         <constant name="pine"/>
      </fact>
      <fact relation="surface-condition">
         <constant name="p1"/>
         <constant name="smooth"/>
      </fact>
      <fact relation="treatment">
         <constant name="p1"/>
         <constant name="varnished"/>
      </fact>
-->
      <fact relation="available">
         <constant name="p2"/>
      </fact>
      <fact relation="colour">
         <constant name="p2"/>
         <constant name="red"/>
      </fact>
      <fact relation="wood">
         <constant name="p2"/>
         <constant name="teak"/>
      </fact>
   </goals>
   <initialTaskNetwork>
      <taskNode name="a:grindNplane" taskSchema="grindNplane">
         <variableDeclaration name="a:grindNplane_part" sort="part"/>
         <variableDeclaration name="a:grindNplane_grindNplane_variable1" sort="surface"/>
         <variableDeclaration name="a:grindNplane_grindNplane_variable2" sort="acolour"/>
         <variableDeclaration name="a:grindNplane_grindNplane_variable3" sort="treatmentstatus"/>
         <variableDeclaration name="a:grindNplane_grindNplane_variable4" sort="surface"/>
         <variableDeclaration name="a:grindNplane_grindNplane_variable5" sort="acolour"/>
         <variableDeclaration name="a:grindNplane_grindNplane_variable6" sort="treatmentstatus"/>
      </taskNode>
      <!--
      <taskNode name="b:grindNPlane" taskSchema="grindNplane">
         <variableDeclaration name="b:grindNPlane_part" sort="part"/>
         <variableDeclaration name="b:grindNPlane_grindNplane_variable1" sort="surface"/>
         <variableDeclaration name="b:grindNPlane_grindNplane_variable2" sort="acolour"/>
         <variableDeclaration name="b:grindNPlane_grindNplane_variable3" sort="treatmentstatus"/>
         <variableDeclaration name="b:grindNPlane_grindNplane_variable4" sort="surface"/>
         <variableDeclaration name="b:grindNPlane_grindNplane_variable5" sort="acolour"/>
         <variableDeclaration name="b:grindNPlane_grindNplane_variable6" sort="treatmentstatus"/>
      </taskNode>
-->
      <taskNode name="c:grindNplane" taskSchema="grindNplane">
         <variableDeclaration name="c:grindNplane_part" sort="part"/>
         <variableDeclaration name="c:grindNplane_grindNplane_variable1" sort="surface"/>
         <variableDeclaration name="c:grindNplane_grindNplane_variable2" sort="acolour"/>
         <variableDeclaration name="c:grindNplane_grindNplane_variable3" sort="treatmentstatus"/>
         <variableDeclaration name="c:grindNplane_grindNplane_variable4" sort="surface"/>
         <variableDeclaration name="c:grindNplane_grindNplane_variable5" sort="acolour"/>
         <variableDeclaration name="c:grindNplane_grindNplane_variable6" sort="treatmentstatus"/>
      </taskNode>
      <!--
      <taskNode name="d:saw" taskSchema="do-saw">
         <variableDeclaration name="d:saw_board" sort="board"/>
         <variableDeclaration name="d:saw_part" sort="part"/>
         <variableDeclaration name="d:saw_do-saw_variable2" sort="awood"/>
         <variableDeclaration name="d:saw_do-saw_variable3" sort="surface"/>
      </taskNode>
      <taskNode name="e:colour" taskSchema="do-colour">
         <variableDeclaration name="e:colour_part" sort="part"/>
         <variableDeclaration name="e:colour_do-colour_variable1" sort="acolour"/>
         <variableDeclaration name="e:colour_do-colour_variable2" sort="machine"/>
      </taskNode>
-->
      <taskNode name="f:colour" taskSchema="do-colour">
         <variableDeclaration name="f:colour_part" sort="part"/>
         <variableDeclaration name="f:colour_do-colour_variable1" sort="acolour"/>
         <variableDeclaration name="f:colour_do-colour_variable2" sort="machine"/>
      </taskNode>
      <valueRestriction type="eq" variable="a:grindNplane_part">
         <constant name="p0"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="c:grindNplane_part">
         <constant name="p2"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="a:grindNplane_grindNplane_variable1">
         <constant name="smooth"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="a:grindNplane_grindNplane_variable2">
         <constant name="red"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="a:grindNplane_grindNplane_variable3">
         <constant name="varnished"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="a:grindNplane_grindNplane_variable4">
         <constant name="smooth"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="a:grindNplane_grindNplane_variable5">
         <constant name="natural"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="a:grindNplane_grindNplane_variable6">
         <constant name="untreated"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="c:grindNplane_grindNplane_variable1">
         <constant name="verysmooth"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="c:grindNplane_grindNplane_variable2">
         <constant name="natural"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="c:grindNplane_grindNplane_variable3">
         <constant name="varnished"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="c:grindNplane_grindNplane_variable4">
         <constant name="smooth"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="c:grindNplane_grindNplane_variable5">
         <constant name="natural"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="c:grindNplane_grindNplane_variable6">
         <constant name="untreated"/>
      </valueRestriction>
      <!--
      <valueRestriction type="eq" variable="b:grindNPlane_part">
         <constant name="p1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="d:saw_part">
         <constant name="p1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="d:saw_board">
         <constant name="b0"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="e:colour_part">
         <constant name="p1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="f:colour_part">
         <constant name="p2"/>
      </valueRestriction>
-->
   </initialTaskNetwork>
</problem>

=== Yuchen1108/panda3core/src/test/resources/de/uniulm/ki/panda3/symbolic/parser/OrganizeMeeting_VerySmall.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE problem SYSTEM "problem-2.0.dtd">
<problem domain="SmartPhone" name="OrganizeMeeting_VerySmall" type="pure-hierarchical">
    <constantDeclaration name="agenda" sort="Agenda"/>
    <constantDeclaration name="contact1" sort="Contact"/>
    <constantDeclaration name="headOfDepartment" sort="Person"/>
    <constantDeclaration name="headOfDepartmentEMailAddress"
                         sort="EMailAddress"/>
    <constantDeclaration name="dateForMeeting" sort="Date"/>
    <constantDeclaration name="email1" sort="EMail"/>
    <constantDeclaration name="account1" sort="EMailAccount"/>
    <constantDeclaration name="room101" sort="Location"/>
    <constantDeclaration name="headOfDepartmentPicture" sort="Picture"/>
    <initialState>
        <fact relation="associated_Contact">
            <constant name="contact1"/>
            <constant name="headOfDepartment"/>
        </fact>
        <fact relation="associated_Picture">
            <constant name="contact1"/>
            <constant name="headOfDepartmentPicture"/>
        </fact>
        <fact relation="created">
            <constant name="contact1"/>
        </fact>
        <fact relation="haveInformation_Contactable">
            <constant name="headOfDepartment"/>
            <constant name="headOfDepartmentEMailAddress"/>
        </fact>
        <fact relation="haveInformation_Regular">
            <constant name="agenda"/>
        </fact>
        <fact relation="haveInformation_Regular">
            <constant name="dateForMeeting"/>
        </fact>
        <fact relation="haveInformation_Regular">
            <constant name="headOfDepartmentPicture"/>
        </fact>
        <fact relation="haveInformation_Regular">
            <constant name="room101"/>
        </fact>
        <fact relation="inMode_Home"/>
        <fact relation="inUse">
            <constant name="contact1"/>
        </fact>
        <fact relation="isFavourite">
            <constant name="contact1"/>
        </fact>
        <fact relation="selected">
            <constant name="account1"/>
        </fact>
    </initialState>
    <goals>
        <fact relation="hasInformation_Regular">
            <constant name="headOfDepartment"/>
            <constant name="dateForMeeting"/>
        </fact>
        <fact relation="hasInformation_Regular">
            <constant name="headOfDepartment"/>
            <constant name="room101"/>
        </fact>
        <fact relation="hasInformation_Regular">
            <constant name="headOfDepartment"/>
            <constant name="agenda"/>
        </fact>
    </goals>
    <initialTaskNetwork>
        <taskNode name="attachMultipleInformationToEmail1" taskSchema="attachMultipleInformation">
            <variableDeclaration
                    name="attachMultipleInformationToEmail1_message" sort="Message"/>
        </taskNode>
        <taskNode name="sendEmail1ToHeadOfDepartment" taskSchema="send_EMail">
            <variableDeclaration name="sendEmail1ToHeadOfDepartment_receipient" sort="Contactable"/>
            <variableDeclaration name="sendEmail1ToHeadOfDepartment_email" sort="EMail"/>
        </taskNode>
        <taskNode name="extractsMultipleInformation_headOfDepartment" taskSchema="extractsMultipleInformation">
            <variableDeclaration
                    name="extractsMultipleInformation_headOfDepartment_contactable" sort="Contactable"/>
            <variableDeclaration
                    name="extractsMultipleInformation_headOfDepartment_message" sort="Message"/>
        </taskNode>
        <orderingConstraint
                predecessor="attachMultipleInformationToEmail1" successor="sendEmail1ToHeadOfDepartment"/>
        <orderingConstraint predecessor="sendEmail1ToHeadOfDepartment" successor="extractsMultipleInformation_headOfDepartment"/>
        <valueRestriction type="eq" variable="attachMultipleInformationToEmail1_message">
            <constant name="email1"/>
        </valueRestriction>
        <valueRestriction type="eq" variable="sendEmail1ToHeadOfDepartment_email">
            <constant name="email1"/>
        </valueRestriction>
        <valueRestriction type="eq" variable="sendEmail1ToHeadOfDepartment_receipient">
            <constant name="headOfDepartment"/>
        </valueRestriction>
        <valueRestriction type="eq" variable="extractsMultipleInformation_headOfDepartment_contactable">
            <constant name="headOfDepartment"/>
        </valueRestriction>
        <valueRestriction type="eq" variable="extractsMultipleInformation_headOfDepartment_message">
            <constant name="email1"/>
        </valueRestriction>
        <causalLink
                consumer="extractsMultipleInformation_headOfDepartment" producer="sendEmail1ToHeadOfDepartment">
            <atomic relation="hasReceived">
                <constant name="headOfDepartment"/>
                <constant name="email1"/>
            </atomic>
        </causalLink>
    </initialTaskNetwork>
</problem>

=== Yuchen1108/panda3core/src/test/resources/de/uniulm/ki/panda3/symbolic/parser/xml/UMTranslog-P-1-AirplanesHub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE problem SYSTEM "problem-2.0.dtd">
<problem domain="UMTranslog" name="umtranslog_1_AirplanesHub" type="pure-hierarchical">
   <documentation>
        There is a solution (with 28 primitive tasks) to this problem after 2466 cycles
        (without using the agent in charge of inserting tasks).
        We can find a solution with 28 primitive tasks (including initial and goal tasks) after 1450 cycles
        in manual mode (with 1372 backtrackings and 5 plans in fringe).
    </documentation>
   <constantDeclaration name="Stuttgart" sort="City"/>
   <constantDeclaration name="BadenWuerttemberg" sort="Region"/>
   <constantDeclaration name="London" sort="City"/>
   <constantDeclaration name="LondonRegion" sort="Region"/>
   <constantDeclaration name="FlughafenStuttgart" sort="Airport"/>
   <constantDeclaration name="Plane_RampStuttgart" sort="Plane_Ramp"/>
   <constantDeclaration name="HeathrowAirport" sort="Airport"/>
   <constantDeclaration name="Plane_RampHeathrow" sort="Plane_Ramp"/>
   <constantDeclaration name="FlughafenParis" sort="Airport_Hub"/>
   <constantDeclaration name="Plane_RampParis" sort="Plane_Ramp"/>
   <constantDeclaration name="FlugzeugLufthansa" sort="Airplane"/>
   <constantDeclaration name="FlugzeugAirFrance" sort="Airplane"/>
   <constantDeclaration name="Stuttgart_Paris_Air_Route"
      sort="Air_Route"/>
   <constantDeclaration name="Paris_London_Air_Route" sort="Air_Route"/>
   <constantDeclaration name="Drucker" sort="Parcels"/>
   <initialState>
      <fact relation="In_Region">
         <constant name="Stuttgart"/>
         <constant name="BadenWuerttemberg"/>
      </fact>
      <fact relation="In_Region">
         <constant name="London"/>
         <constant name="LondonRegion"/>
      </fact>
      <fact relation="In_City">
         <constant name="FlughafenStuttgart"/>
         <constant name="Stuttgart"/>
      </fact>
      <fact relation="Available">
         <constant name="FlughafenStuttgart"/>
      </fact>
      <fact relation="At_Equipment">
         <constant name="Plane_RampStuttgart"/>
         <constant name="FlughafenStuttgart"/>
      </fact>
      <fact relation="Available">
         <constant name="Plane_RampStuttgart"/>
      </fact>
      <fact relation="In_City">
         <constant name="HeathrowAirport"/>
         <constant name="London"/>
      </fact>
      <fact relation="Available">
         <constant name="HeathrowAirport"/>
      </fact>
      <fact relation="At_Equipment">
         <constant name="Plane_RampHeathrow"/>
         <constant name="HeathrowAirport"/>
      </fact>
      <fact relation="Available">
         <constant name="Plane_RampHeathrow"/>
      </fact>
      <fact relation="Available">
         <constant name="FlughafenParis"/>
      </fact>
      <fact relation="At_Equipment">
         <constant name="Plane_RampParis"/>
         <constant name="FlughafenParis"/>
      </fact>
      <fact relation="Available">
         <constant name="Plane_RampParis"/>
      </fact>
      <fact relation="Serves">
         <constant name="FlughafenParis"/>
         <constant name="BadenWuerttemberg"/>
      </fact>
      <fact relation="Serves">
         <constant name="FlughafenParis"/>
         <constant name="LondonRegion"/>
      </fact>
      <fact relation="At_Vehicle">
         <constant name="FlugzeugLufthansa"/>
         <constant name="FlughafenStuttgart"/>
      </fact>
      <fact relation="At_Vehicle">
         <constant name="FlugzeugAirFrance"/>
         <constant name="FlughafenParis"/>
      </fact>
      <fact relation="Connects">
         <constant name="Stuttgart_Paris_Air_Route"/>
         <constant name="FlughafenStuttgart"/>
         <constant name="FlughafenParis"/>
      </fact>
      <fact relation="Connects">
         <constant name="Paris_London_Air_Route"/>
         <constant name="FlughafenParis"/>
         <constant name="HeathrowAirport"/>
      </fact>
      <fact relation="Available">
         <constant name="Stuttgart_Paris_Air_Route"/>
      </fact>
      <fact relation="Available">
         <constant name="Paris_London_Air_Route"/>
      </fact>
      <fact relation="Available">
         <constant name="FlugzeugAirFrance"/>
      </fact>
      <fact relation="Available">
         <constant name="FlugzeugLufthansa"/>
      </fact>
      <fact relation="PV_Compatible">
         <constant name="Drucker"/>
         <constant name="FlugzeugAirFrance"/>
      </fact>
      <fact relation="PV_Compatible">
         <constant name="Drucker"/>
         <constant name="FlugzeugLufthansa"/>
      </fact>
      <fact relation="RV_Compatible">
         <constant name="Stuttgart_Paris_Air_Route"/>
         <constant name="FlugzeugLufthansa"/>
      </fact>
      <fact relation="RV_Compatible">
         <constant name="Paris_London_Air_Route"/>
         <constant name="FlugzeugAirFrance"/>
      </fact>
      <fact relation="At_Package">
         <constant name="Drucker"/>
         <constant name="FlughafenStuttgart"/>
      </fact>
   </initialState>
   <goals>
      <fact relation="Delivered">
         <constant name="Drucker"/>
      </fact>
   </goals>
   <initialTaskNetwork>
      <taskNode name="transport_Kunde1" taskSchema="transport">
         <variableDeclaration name="tk1_p" sort="Package"/>
         <variableDeclaration name="tk1_from" sort="Location"/>
         <variableDeclaration name="tk1_to" sort="Location"/>
      </taskNode>
      <valueRestriction type="eq" variable="tk1_p">
         <constant name="Drucker"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="tk1_from">
         <constant name="FlughafenStuttgart"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="tk1_to">
         <constant name="HeathrowAirport"/>
      </valueRestriction>
   </initialTaskNetwork>
</problem>

=== Yuchen1108/panda3core/src/test/resources/de/uniulm/ki/panda3/symbolic/parser/xml/OrganizeMeeting_VeryVerySmall.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE problem SYSTEM "problem-2.0.dtd">
<problem domain="SmartPhone" name="OrganizeMeeting_VeryVerySmall" type="pure-hierarchical">
   <constantDeclaration name="agenda" sort="Agenda"/>
   <constantDeclaration name="contact1" sort="Contact"/>
   <constantDeclaration name="headOfDepartment" sort="Person"/>
   <constantDeclaration name="headOfDepartmentEMailAddress"
      sort="EMailAddress"/>
   <constantDeclaration name="dateForMeeting" sort="Date"/>
   <constantDeclaration name="email1" sort="EMail"/>
   <constantDeclaration name="account1" sort="EMailAccount"/>
   <constantDeclaration name="room101" sort="Location"/>
   <constantDeclaration name="headOfDepartmentPicture" sort="Picture"/>
   <initialState>
      <fact relation="associated_Contact">
         <constant name="contact1"/>
         <constant name="headOfDepartment"/>
      </fact>
      <fact relation="associated_Picture">
         <constant name="contact1"/>
         <constant name="headOfDepartmentPicture"/>
      </fact>
      <fact relation="created">
         <constant name="contact1"/>
      </fact>
      <fact relation="haveInformation_Contactable">
         <constant name="headOfDepartment"/>
         <constant name="headOfDepartmentEMailAddress"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="agenda"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="dateForMeeting"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="headOfDepartmentPicture"/>
      </fact>
      <fact relation="haveInformation_Regular">
         <constant name="room101"/>
      </fact>
      <fact relation="inMode_Home"/>
      <fact relation="inUse">
         <constant name="contact1"/>
      </fact>
      <fact relation="isFavourite">
         <constant name="contact1"/>
      </fact>
      <fact relation="selected">
         <constant name="account1"/>
      </fact>
   </initialState>
   <goals>
      <fact relation="hasInformation_Regular">
         <constant name="headOfDepartment"/>
         <constant name="dateForMeeting"/>
      </fact>
   </goals>
   <initialTaskNetwork>
      <taskNode name="attachInformationToEmail1" taskSchema="attachInformationToEMail">
         <variableDeclaration name="attachInformationToEmail1_email" sort="EMail"/>
         <variableDeclaration name="attachInformationToEmail1_information" sort="TransferableByEmail"/>
      </taskNode>
      <taskNode name="sendEmail1ToHeadOfDepartment" taskSchema="send_EMail">
         <variableDeclaration name="sendEmail1ToHeadOfDepartment_receipient" sort="Contactable"/>
         <variableDeclaration name="sendEmail1ToHeadOfDepartment_email" sort="EMail"/>
      </taskNode>
      <taskNode name="extractsInformation_headOfDepartment" taskSchema="extractsInformation">
         <variableDeclaration
            name="extractsInformation_headOfDepartment_receiver" sort="Contactable"/>
         <variableDeclaration
            name="extractsInformation_headOfDepartment_email" sort="Message"/>
         <variableDeclaration
            name="extractsInformation_headOfDepartment_information" sort="Information"/>
      </taskNode>
      <orderingConstraint predecessor="sendEmail1ToHeadOfDepartment" successor="extractsInformation_headOfDepartment"/>
      <orderingConstraint predecessor="attachInformationToEmail1" successor="extractsInformation_headOfDepartment"/>
      <valueRestriction type="eq" variable="attachInformationToEmail1_email">
         <constant name="email1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="sendEmail1ToHeadOfDepartment_email">
         <constant name="email1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="sendEmail1ToHeadOfDepartment_receipient">
         <constant name="headOfDepartment"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="extractsInformation_headOfDepartment_email">
         <constant name="email1"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="extractsInformation_headOfDepartment_information">
         <constant name="dateForMeeting"/>
      </valueRestriction>
      <valueRestriction type="eq" variable="extractsInformation_headOfDepartment_receiver">
         <constant name="headOfDepartment"/>
      </valueRestriction>
	  <valueRestriction type="eq" variable="attachInformationToEmail1_information">
         <constant name="dateForMeeting"/>
      </valueRestriction>
      <causalLink consumer="extractsInformation_headOfDepartment" producer="attachInformationToEmail1">
         <atomic relation="attached">
            <constant name="email1"/>
            <constant name="dateForMeeting"/>
         </atomic>
      </causalLink>
      <causalLink consumer="extractsInformation_headOfDepartment" producer="sendEmail1ToHeadOfDepartment">
         <atomic relation="hasReceived">
            <constant name="headOfDepartment"/>
            <constant name="email1"/>
         </atomic>
      </causalLink>
   </initialTaskNetwork>
</problem>
